### ISSUE TITLE
python版本问题

### ISSUE THREAD

**Issue by yjh123ty** [Musule/MindMake#5]
你好，我在本地(windows 7)clone下来，首先没有dist文件夹。其次，python版本请问能支持3.x吗？我目前环境是3.x报错。。。

**Comment by liyinchigithub** [comment]
你好，感谢你的提醒，我已重新上传上去。请再重新克隆一份，或者执行git pull 命令拉取最新代码，就可以看到dist文件。（导致看不到的原因，我在git忽略文件.ignore中加入了/dist/，所以导致没有上传至github）
python版本没有限制，但要求你的电脑有安装配置nodejs环境。

https://www.runoob.com/nodejs/nodejs-install-setup.html
